name: 'Build infer for macOS'
description: 'This action build infer'
inputs:
  infer_version:
    description: 'infer version. [latest,vX.Y.Z]'
    default: 'latest'
outputs:
  infer_version:
    description: 'installed infer version'
    value: ${{ steps.install.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Get build script
      shell: bash
      id: build-script
      env:
        INPUTS_INFER_VERSION: ${{ steps.resolve.outputs.version }}
      run: |
        curl -sSL --retry 3 -o "${{ runner.temp }}/build-infer.sh" "https://raw.githubusercontent.com/facebook/infer/${INPUTS_INFER_VERSION}/build-infer.sh" 
        INFER_OPAM_DEFAULT_SWITCH=$(grep -oE "INFER_OPAM_DEFAULT_SWITCH.*" "${{ runner.temp }}/build-infer.sh" | head -n 1)
        if [ -n "${INFER_OPAM_DEFAULT_SWITCH}" ]; then
          echo "${INFER_OPAM_DEFAULT_SWITCH//\"/}" >> "${GITHUB_OUTPUT}"
        fi
    - name: Set-up automake
      uses: srz-zumix/setup-automake@v0
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "${{ steps.build-script.outputs.INFER_OPAM_DEFAULT_SWITCH }}"
    - name: Opam switch create
      shell: bash
      env:
        OPAM_SWITCH: "${{ steps.build-script.outputs.INFER_OPAM_DEFAULT_SWITCH }}"
        OPAM_COMPILER: "${{ steps.build-script.outputs.INFER_OPAM_DEFAULT_SWITCH }}"
      run: |
        opam switch create "${OPAM_SWITCH}" "${OPAM_COMPILER}"
    - name: Build Infer
      shell: bash
      id: build
      env:
        INPUTS_INFER_VERSION: ${{ steps.resolve.outputs.version }}
        INFER_BUILD_OPTIONS: --user-opam-switch
      run: |
        "${GITHUB_ACTION_PATH}/build.sh"
