name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'BREAKING CHANGES'
    labels:
      - 'BREAKING CHANGE'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Dependency'
    labels:
      - 'dependency'
      - 'dependencies'
      - 'renovate'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'security'
  - title: 'Documentation'
    labels:
      - 'document'
      - 'documents'
      - 'documentation'
  - title: 'Internal improvement'
    labels:
      - 'CI'
exclude-labels:
  - 'invalid'
  - 'internal-fix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'BREAKING CHANGE'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'dependency'
      - 'fix'
      - 'bug'
      - 'security'
  default: minor
template: |
  [Compare $PREVIOUS_TAG with v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)

  ## Changes

  $CHANGES
