name: 'Setup infer'
description: 'This action sets up infer'
inputs:
  infer_version:
    description: 'infer version. [latest,vX.Y.Z]'
    default: 'latest'
outputs:
  infer_version:
    description: 'installed infer version'
    value: ${{ steps.install.outputs.version }}

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/install.sh
      shell: bash
      id: install
      env:
        INFER_VERSION: ${{ inputs.infer_version }}
    - run: |
        echo "::group::📖 infer -h"
        infer -h 2>&1 || true
        echo "::endgroup::"
      shell: bash

branding:
  icon: 'book'
  color: 'blue'
