name: 'Setup infer'
description: 'This action sets up infer'
inputs:
  infer_version:
    description: 'infer version. [latest,vX.Y.Z]'
    default: 'latest'
outputs:
  infer_version:
    description: 'installed infer version'
    value: ${{ steps.install.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Resolve infer version
      shell: bash
      id: resolve
      env:
        INPUTS_INFER_VERSION: ${{ inputs.infer_version }}
      run: |
        "${GITHUB_ACTION_PATH}/resolve.sh"
    - name: Get build script
      if: runner.os == 'macOS'
      shell: bash
      id: build-script
      env:
        INPUTS_INFER_VERSION: ${{ steps.resolve.outputs.version }}
      run: |
        curl -sSL -o "${{ runner.temp }}/build-infer.sh" "https://raw.githubusercontent.com/facebook/infer/${INPUTS_INFER_VERSION}/build-infer.sh" 
        INFER_OPAM_DEFAULT_SWITCH=$(grep -oE "INFER_OPAM_DEFAULT_SWITCH.*" "${{ runner.temp }}/build-infer.sh" | head -n 1)
        if [ -n "${INFER_OPAM_DEFAULT_SWITCH}" ]; then
          printenv INFER_OPAM_DEFAULT_SWITCH >> "${GITHUB_OUTPUT}"
        fi
    - name: Set-up OCaml
      if: runner.os == 'macOS'
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "${{ steps.build-script.outputs.INFER_OPAM_DEFAULT_SWITCH }}"
    - name: Install Infer
      shell: bash
      id: install
      env:
        INPUTS_INFER_VERSION: ${{ steps.resolve.outputs.version }}
        INFER_BUILD_OPTIONS: "--user-opam-switch"
      run: |
        "${GITHUB_ACTION_PATH}/install.sh"
    - name: Infer Help
      shell: bash
      run: |
        echo "::group::📖 infer -h"
        infer -h 2>&1 || true
        echo "::endgroup::"

branding:
  icon: 'book'
  color: 'blue'
