name: 'Setup infer'
description: 'This action sets up infer'
inputs:
  infer_version:
    description: 'infer version. [latest,vX.Y.Z]'
    default: 'latest'
  github_token:
    description: 'GitHub Token'
    default: ''
outputs:
  infer_version:
    description: 'installed infer version'
    value: ${{ steps.install.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Resolve infer version
      shell: bash
      id: resolve
      env:
        INPUTS_INFER_VERSION: ${{ inputs.infer_version }}
        INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        "${GITHUB_ACTION_PATH}/resolve.sh"
    - name: Install Infer
      shell: bash
      id: install
      env:
        INPUTS_INFER_VERSION: ${{ steps.resolve.outputs.version }}
        INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ github.token }}
        INFER_BUILD_OPTIONS: --user-opam-switch
      run: |
        "${GITHUB_ACTION_PATH}/install.sh"
    - uses: srz-zumix/setup-infer/.github/actions/build-infer-macos@main
      if: runner.os == 'macOS' && steps.install.outputs.installed == 'false'
      with:
        infer_version: ${{ steps.resolve.outputs.version }}
    - name: Infer Help
      shell: bash
      run: |
        echo "::group::📖 infer -h"
        infer -h 2>&1 || true
        echo "::endgroup::"

branding:
  icon: 'book'
  color: 'blue'
