name: SelfTest
on:
  pull_request:

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          # - macos-latest
    steps:
    - name: clone
      uses: actions/checkout@v4
    - uses: ./
      id: setup
    - run: |
        infer --help | grep "${{ steps.setup.outputs.infer_version }}"
